import type { Metadata } from 'next'
import './globals.css'
import Header from '@/components/header/page'
import Footer from '@/components/footer/page'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className='flex , flex-col justify-center  '>
        <Header />
        <div className='my-9'>
          {children}
        </div>
        <Footer />
      </body>
    </html>
  )
}
